#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace SampleModel
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class SampleContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public SampleContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SampleModel.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SampleModel.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<SampleModel.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SampleModel.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SampleModel.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<SampleModel.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SampleModel.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SampleModel.Opportunity> OpportunitySet
		{
			get
			{
				return this.CreateQuery<SampleModel.Opportunity>();
			}
		}
	}
}
#pragma warning restore CS1591
