#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Type de besoin
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum need
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Doit = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Devrait = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Intressant = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aucunbesoin = 3,
	}
}
#pragma warning restore CS1591
