#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Code de l’erreur de tarification.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum qooi_pricingerrorcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aucun = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dtailsdelerreur = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Niveaudeprixmanquant = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Niveaudeprixinactif = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quantitmanquante = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prixunitairemanquant = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Produitmanquant = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Produitnonvalide = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Codedetarificationmanquant = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Codedetarificationnonvalide = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unitdemesuremanquante = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Produitabsentduniveaudeprix = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Montantduniveaudeprixmanquant = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pourcentageduniveaudeprixmanquant = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prixmanquant = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cotactuelmanquant = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cotstandardmanquant = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Montantduniveaudeprixnonvalide = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pourcentageduniveaudeprixnonvalide = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prixnonvalide = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cotactuelnonvalide = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cotstandardnonvalide = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rgledarrondinonvalide = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Optiondarrondinonvalide = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Montantdarrondinonvalide = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Erreurdecalculduprix = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Typederemisenonvalide = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		tatdutypederemisenonvalide = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Remisenonvalide = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quantitnonvalide = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prcisiondetarificationnonvalide = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unitdemesurepardfautduproduitmanquante = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planificationdesunitsdemesureduproduitmanquantes = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Typederemiseinactif = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Devisedeniveaudeprixnonvalide = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attributdeprixhorsdelintervalleadmis = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributdevisedebaseDpassementdecapacitsuprieur = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributdevisedebaseDpassementdecapacitinfrieur = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ladevisedetransactionnestpasdfiniepourllmenttarifaire = 38,
	}
}
#pragma warning restore CS1591
