#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Phase du processus de vente dans laquelle se trouve cette entité.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum opportunity_salesstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualifier = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dvelopper = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Proposer = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fermer = 3,
	}
}
#pragma warning restore CS1591
