#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Délai d'exécution pendant lequel ce prospect est susceptible d'effectuer un achat.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum purchasetimeframe
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Immdiat = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cetrimestre = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letrimestreprochain = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cetteanne = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inconnu = 4,
	}
}
#pragma warning restore CS1591
