#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Type de procédure d'achat pour ce prospect.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum purchaseprocess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individuel = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Comit = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inconnu = 2,
	}
}
#pragma warning restore CS1591
