#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleModel
{
	
	
	/// <summary>
	/// Langues Power Pages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum powerpagelanguages
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arabe = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BasqueBasque = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulgareBulgarie = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalanCatalan = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChinoisChine = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChinoisHongKong_RAS = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChinoisTraditionnel = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CroateCroatie = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TchqueRpubliquetchque = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DanoisDanemark = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NerlandaisPaysBas = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Anglais = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstonienEstonie = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinnoisFinlande = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FranaisFrance = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GalicienEspagne = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AllemandAllemagne = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GrecGrce = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hbreu = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HindiInde = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HongroisHongrie = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndonsienIndonsie = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ItalienItalie = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JaponaisJapon = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KazakhKazakhstan = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CorenCoreduSud = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LettonLettonie = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LituanienLituanie = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MalaisMalaisie = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Norvgien_BokmlNorvge = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PolonaisPologne = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortugaisBrsil = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortugaisPortugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoumainRoumanie = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RusseRussie = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Serbe_cyrilliqueSerbie = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Serbe_latinSerbie = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovaqueSlovaquie = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovneSlovnie = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Espagnol_traditionnelEspagne = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SudoisSude = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThaThalande = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TurcTurquie = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UkrainienUkraine = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VietnamienVietnam = 1066,
	}
}
#pragma warning restore CS1591
